(ql:quickload 'arrow-macros)
(ql:quickload 'uiop)
(ql:quickload 'alexandria)
(ql:quickload 'str)
(defpackage :day1
  (:use :cl :arrow-macros))

(in-package :day1)

; Part 1
(defun part1 ()
  (let* ((lines (uiop:read-file-lines "day1-input.txt"))
         (pairs (mapcar #'str:words lines))
         (left (mapcar (lambda (pair)
                         (parse-integer (first pair)))
                       pairs))
         (right (mapcar (lambda (pair)
                          (parse-integer (second pair)))
                        pairs)))
    (loop for i in (mapcar (lambda (l r) (abs (- l r)))
                           (sort left #'<)
                           (sort right #'<))
          summing i)))
(part1)

; Part 2
(defun part2 ()
  (let* ((lines (uiop:read-file-lines "day1-input.txt"))
         (pairs (mapcar #'str:words lines))
         (left (mapcar (lambda (pair)
                         (parse-integer (first pair)))
                       pairs))
         (right (mapcar (lambda (pair)
                          (parse-integer (second pair)))
                        pairs)))
    (loop for l in left summing (* l (count l right)))))
(part2)
